# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Tripme' do
use_frameworks!
pod "PayPal-iOS-SDK", "~> 2.10.2"
end

target 'TripmeTests' do

end

target 'TripmeUITests' do

end

